### ISSUE TITLE
This doesn't work; it hides immediately after install, and apparently can't be activated

### ISSUE THREAD

**Issue by givihuda** [itsHobbes/div-highlighter#1]
What is going on with this? It showed up then disappeared in the bar... I changed it so it would have to be activated upon click, but that didn't make it appear.

Also my internet started lagging after it installed, and a website I was working with started denying me.

Is this malicious? Is it non-functional? When I went to report the extension after uninstalling it, there's an option "Does not work" with a link to Google support that mentions it'll hide if it just "won't work"... OK, so I don't know what it's doing but I did notice it has a permission to see all history... what's the point of that?!

**Comment by itsHobbes** [comment]
Works perfectly fine for me. You haven't really given any details at all. So please be more specific as to what your problem is, and the steps you took to encounter the problem.

You are also totally incorrect in stating this extension has access to your history. It does not have access to chrome history. It's permissions as you can see [here](https://github.com/itsHobbes/div-highlighter/blob/master/manifest.json#L18-L22) allow it to view your chrome tabs (this is required to highlight divs which is the purpose of this extension) and it allows the extension access to any website you access, again required for the purpose of the extension.

**Comment by itsHobbes** [comment]
Closing this since you haven't responded.
